Application deployment
DNXLabs/one-cli pull request #22
Opened 2020-05-08 10:54 UTC by adenot

2020-05-18 01:48 UTC, adenot commented
this is the version of one.yaml that i'm working with this PR:
```
images:
  terraform: dnxsolutions/terraform:0.12.24-dnx1
  gsuite: dnxsolutions/aws-google-auth:latest
  aws: dnxsolutions/aws:1.18.44-dnx2
  ecs-deploy: dnxsolutions/ecs-deploy:1.1.0

# repository-url: 335071203852.dkr.ecr.ap-southeast-2.amazonaws.com/copacabana
app:
  name: copacabana
  port: 80
  docker:
    file: Dockerfile
    registry-type: ecr
    registry-options:
      ecr-aws-account-id: 335071203852
      ecr-aws-region: ap-southeast-2
      ecr-repository: copacabana
  ecs-task-definition-file: task-definition.tpl.json

workspaces:
  dev:
    type: ecs-deploy
    aws-account-id: 663974054766
    aws-role: dnx-labs-admin
    aws-assume-role: true
    aws-region: ap-southeast-2
    ecs-cluster-name: allan-01
```

2020-05-18 01:49 UTC, adenot commented
this is the version of one.yaml that i'm working with this PR:

```
images:
  terraform: dnxsolutions/terraform:0.12.24-dnx1
  gsuite: dnxsolutions/aws-google-auth:latest
  aws: dnxsolutions/aws:1.18.44-dnx2
  ecs-deploy: dnxsolutions/ecs-deploy:1.1.0

# repository-url: <REDACTED>.dkr.ecr.ap-southeast-2.amazonaws.com/copacabana
app:
  name: copacabana
  port: 80
  docker:
    file: Dockerfile
    registry-type: ecr
    registry-options:
      ecr-aws-account-id: <REDACTED>
      ecr-aws-region: ap-southeast-2
      ecr-repository: copacabana
  ecs-task-definition-file: task-definition.tpl.json

workspaces:
  dev:
    type: ecs-deploy
    aws-account-id: <REDACTED>
    aws-role: <REDACTED>
    aws-assume-role: true
    aws-region: ap-southeast-2
    ecs-cluster-name: allan-01
```

2020-06-08 15:47 UTC, arthurbdiniz commented
I think that before we merge this into master would be good to clean the commits and it's messages.

So to not override this branch I made this clean up in another branch to then decide if it's good
https://github.com/DNXLabs/one-cli/commits/feature/app-deploy-clean

2020-06-09 01:43 UTC, arthurbdiniz commented on one/commands/login.py
> +    container.create(image=azure_auth_image, command=None, environment=env_idp)
Volume should exist to store .env file from the container on the host.

2020-06-09 01:43 UTC, arthurbdiniz commented on one/commands/login.py
> +    container.create(image=gsuite_auth_image, command=None, environment=env_idp)
Volume should exist to store .env file from the container on the host.

2020-06-09 02:01 UTC, arthurbdiniz requested changes
- [x] Need squash some rollback commits
- [x] Fresh start breaks login, always request login when `credentials` are not in the folder.

2020-06-09 11:59 UTC, arthurbdiniz approved these changes

2020-06-09 12:00 UTC, merged